In [1]:
import os
import subprocess
import re
import shutil
import pandas as pd
import time
import random

# Youtube Downloading
YT-DLP: https://github.com/yt-dlp/yt-dlp  
FFmpeg: https://www.ffmpeg.org/download.html

In [2]:
!python --version
!where python
!pip --version
# !where pip

Python 3.12.10
c:\Python\Python312\python.exe
C:\Users\rob_t\AppData\Local\Microsoft\WindowsApps\python.exe
pip 26.0.1 from C:\Python\Python312\Lib\site-packages\pip (python 3.12)

In [3]:
# Check current directory and list contents
import os
print("Current directory:", os.getcwd())
print("Contents:", os.listdir())

Current directory: c:\Users\rob_t\repos\y_media
Contents: ['.git', '.gitignore', 'ffmpeg-8.0.1-essentials_build', 'loop_n_fading.ipynb', 'Past Lives_1hour.mp3', 'README.md', 'twitter_cookies.txt', 'youtube_cookies.txt', 'yt-dlp', 'yt-dlp.ipynb', 'yt-dlp_s4.ipynb']

In [4]:
# Method 1: Using shell command with full path
# Linux/MacOS
# !./yt-dlp/yt-dlp.exe --version
# Windows
!yt-dlp\yt-dlp.exe --version  # Use backslash for Windows paths
print()
!ffmpeg-8.0.1-essentials_build\bin\ffmpeg.exe -version

# Method 2: For playlist URLs, use this format:
# !./yt-dlp/yt-dlp.exe --flat-playlist --print "%(url)s" "https://www.youtube.com/playlist?list=YOUR_PLAYLIST_ID"

# Example for downloading:
# !./yt-dlp/yt-dlp.exe -f "best[height<=720]" -o "downloads/%(title)s.%(ext)s" "YOUR_URL_HERE"

2026.03.13

ffmpeg version 8.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers
built with gcc 15.2.0 (Rev8, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-openal --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      60.  8.100 / 60.  8.100
libavcodec     62. 11.100 / 62. 11.100
libavformat    62.  3.100 / 62.  3.100
libavdevice    62.  1.100 / 62.  1.100
libavfilter    11.  4.100 / 11.  4.100
libswscale      9.  1.100 /  9.  1.100
libswresample   6.  1.100 /  6.  1.100

Exiting with exit code 0

In [5]:
# WORKING ROUTE FOR YT-DLP
# =========================

# Step 1: Define the yt-dlp executable path
# Set the path to yt-dlp executable (we're already in the yt-dlp directory)
ytdlp_path = "yt-dlp\yt-dlp.exe"
ffmpeg_path = "ffmpeg-8.0.1-essentials_build\\bin"  # "ffmpeg-7.1.1-essentials_build\\bin" 

# Step 2: Create helper function for running yt-dlp commands
def run_ytdlp(args):
    """Helper function to run yt-dlp commands"""
    cmd = [ytdlp_path] + args + ["--ffmpeg-location", ffmpeg_path]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=os.getcwd())
        print("STDOUT:", result.stdout)
        if result.stderr:
            print("STDERR:", result.stderr)
        return result
    except Exception as e:
        print(f"Error running yt-dlp: {e}")
        return None

# Step 3: Test the setup
print("Testing yt-dlp setup...")
run_ytdlp(["--version"])

Testing yt-dlp setup...

<>:6: SyntaxWarning: invalid escape sequence '\y'
<>:6: SyntaxWarning: invalid escape sequence '\y'
C:\Users\rob_t\AppData\Local\Temp\ipykernel_13524\1210210038.py:6: SyntaxWarning: invalid escape sequence '\y'
  ytdlp_path = "yt-dlp\yt-dlp.exe"

STDOUT: 2026.03.13

CompletedProcess(args=['yt-dlp\\yt-dlp.exe', '--version', '--ffmpeg-location', 'ffmpeg-8.0.1-essentials_build\\bin'], returncode=0, stdout='2026.03.13\n', stderr='')

In [6]:
def list_playlist_urls(completed_process):
    """List all URLs in a YouTube playlist"""
    if completed_process and completed_process.stdout:
        urls = completed_process.stdout.strip().split('\n')
        return urls
    else:
        print("No URLs found or error occurred.")
        return []

```python
# Chỉ title (hiện tại)
"%(title)s.%(ext)s"

# Title + ID (như file cũ)
"%(title)s [%(id)s].%(ext)s"

# Title + Uploader + ID
"%(uploader)s - %(title)s [%(id)s].%(ext)s"

# Date + Title + ID
"%(upload_date)s - %(title)s [%(id)s].%(ext)s"
```

In [7]:
# PRACTICAL EXAMPLES
# ==================

# Example 1: Get video info
def get_video_info(url):
    """Get video information"""
    args = ["--dump-json", url]
    return run_ytdlp(args)

# Example 2: List playlist URLs
def get_playlist_urls(playlist_url):
    """List all URLs in a playlist"""
    args = ["--flat-playlist", "--print", "%(url)s", playlist_url]
    return run_ytdlp(args)

# Example 3: Download with specific format
def download_video(url, output_dir="downloads"):
    """Download video with specific settings"""
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    args = [
        "-f", "best[height<=1080]",  # Max 1080p quality
        "-o", f"D:/downloaded_media/{output_dir}/%(title)s [%(id)s].%(ext)s",  # Output filename pattern
        "--restrict-filenames", # ✅ GIẢI PHÁP: Bỏ dấu tiếng Việt và ký tự đặc biệt trong tên file
        url
    ]
    return run_ytdlp(args)

# Example 4: Download audio only
def download_audio(url, output_dir="audio"):
    """Download audio only"""
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    args = [
        "-x",  # Extract audio
        "--audio-format", "best",  # Convert to format in list [best (default), aac, alac, flac, m4a, mp3, opus, vorbis, wav]
        "-o", f"D:/downloaded_media/{output_dir}/%(title)s [%(id)s].%(ext)s",
        "--restrict-filenames", # ✅ GIẢI PHÁP: Bỏ dấu tiếng Việt và ký tự đặc biệt trong tên file
        url
    ]
    return run_ytdlp(args)

# Example 5: Download best video (Video + Audio)
def download_best_video2(url, output_dir="unlisted"):
    """Download best video (Video + Audio)"""
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    args = [
        "-f", "bestvideo+bestaudio/best",  # Best video + best audio
        "-o", f"D:/downloaded_media/{output_dir}/%(title)s [%(id)s].%(ext)s",
        "--restrict-filenames", # ✅ GIẢI PHÁP: Bỏ dấu tiếng Việt và ký tự đặc biệt trong tên file
        url
    ]
    return run_ytdlp(args)

def download_best_video(
    url,
    output_dir="unlisted",
    # cookies_file="twitter_cookies.txt",
    cookies_file="youtube_cookies.txt",
    node_path=r"C:\Program Files\nodejs\node.exe"
):
    """Download best video (Video + Audio) from X/Twitter (Brave-safe)"""

    # Normalize domain
    url = re.sub(r"https?://(www\.)?x\.com", "https://twitter.com", url)

    base_dir = f"D:/downloaded_media/{output_dir}"
    # base_dir = f"E:/downloaded_media/{output_dir}"
    os.makedirs(base_dir, exist_ok=True)

    args = [
        "--js-runtimes", f"node:{node_path}", # Fix JS Runtime
        "--encoding", "utf-8", # FIX UnicodeDecodeError
        "--cookies", cookies_file,              # ✅ ONLY THIS
        "--no-playlist",
        "--merge-output-format", "mp4",
        # f-string cho output để tránh lỗi đường dẫn Windows
        "-o", f"{base_dir}/%(title)s [%(id)s].%(ext)s",

        # ✅ GIẢI PHÁP: Bỏ dấu tiếng Việt và ký tự đặc biệt trong tên file
        "--restrict-filenames", 
        
        # ✅ Đảm bảo encoding là UTF-8 để nhận diện tiêu đề đúng trước khi format
        "--recode-video", "mp4",
        
        "-f", "bestvideo+bestaudio/best",
        url
    ]

    return run_ytdlp(args)


print("Helper functions defined successfully!")
print("Available functions:")
print("- get_video_info(url)")
print("- get_playlist_urls(playlist_url)")
print("- download_video(url, output_dir='downloads')")
print("- download_audio(url, output_dir='audio')")
print("- download_unlisted_video(url, output_dir='unlisted')")

Helper functions defined successfully!
Available functions:
- get_video_info(url)
- get_playlist_urls(playlist_url)
- download_video(url, output_dir='downloads')
- download_audio(url, output_dir='audio')
- download_unlisted_video(url, output_dir='unlisted')

In [ ]:
# USAGE EXAMPLES
# ===============

# Example: Test with a playlist (replace with your actual playlist URL)
# playlist_url = "https://www.youtube.com/playlist?list=YOUR_PLAYLIST_ID"
# list_playlist_urls(playlist_url)

# Example: Test with a single video (replace with your actual video URL)
# video_url = "https://www.youtube.com/watch?v=YOUR_VIDEO_ID"
# get_video_info(video_url)

# Example: Download a video
# download_video(video_url, "downloads")

# Example: Download audio only
# download_audio(video_url, "audio")

# For your specific use case, to list playlist URLs:
print("To use with a playlist, replace YOUR_PLAYLIST_ID and run:")
print('list_playlist_urls("https://www.youtube.com/playlist?list=YOUR_PLAYLIST_ID")')

print("\nTo download videos from your existing folders:")
print("Current audio folders found:")
for folder in ["edm", "edm - no lyric", "remix"]:
    folder = os.path.join("audio", folder)
    if os.path.exists(folder):
        files = [f for f in os.listdir(folder) if f.endswith('.opus')]
        print(f"  {folder}: {len(files)} files")
        if files:
            print(f"    Example: {files[0]}")

To use with a playlist, replace YOUR_PLAYLIST_ID and run:
list_playlist_urls("https://www.youtube.com/playlist?list=YOUR_PLAYLIST_ID")

To download videos from your existing folders:
Current audio folders found:

### Download one audio

In [9]:
url = input("Enter Youtube URL to download audio: ")
download_audio(url)

STDOUT: [youtube] Extracting URL: https://youtu.be/2B9jv7prFno?si=VekCYNu7hpLbRNC6
[youtube] 2B9jv7prFno: Downloading webpage
[youtube] 2B9jv7prFno: Downloading android vr player API JSON
[info] 2B9jv7prFno: Downloading 1 format(s): 251
[download] Destination: D:\downloaded_media\audio\Memory_of_Lightwaves_~_Relaxing_FFX-2_Music_w_Ocean_and_Soft_Rain_Sounds [2B9jv7prFno].webm

[download]   0.0% of   31.50MiB at  867.85KiB/s ETA 00:37
[download]   0.0% of   31.50MiB at    2.54MiB/s ETA 00:12
[download]   0.0% of   31.50MiB at    3.02MiB/s ETA 00:10
[download]   0.0% of   31.50MiB at    6.47MiB/s ETA 00:04
[download]   0.1% of   31.50MiB at  189.31KiB/s ETA 02:50
[download]   0.2% of   31.50MiB at  381.86KiB/s ETA 01:24
[download]   0.4% of   31.50MiB at  609.27KiB/s ETA 00:52
[download]   0.8% of   31.50MiB at    1.05MiB/s ETA 00:29
[download]   1.6% of   31.50MiB at    1.68MiB/s ETA 00:18
[download]   3.2% of   31.50MiB at    1.73MiB/s ETA 00:17
[download]   6.3% of   31.50MiB at    1.93MiB/s ETA 00:15
[download]  12.7% of   31.50MiB at    2.31MiB/s ETA 00:11
[download]  21.8% of   31.50MiB at    2.90MiB/s ETA 00:08
[download]  30.2% of   31.50MiB at    2.96MiB/s ETA 00:07
[download]  30.2% of   31.50MiB at  Unknown B/s ETA Unknown
[download]  30.2% of   31.50MiB at  Unknown B/s ETA Unknown
[download]  30.2% of   31.50MiB at    6.56MiB/s ETA 00:03
[download]  30.3% of   31.50MiB at   14.05MiB/s ETA 00:01
[download]  30.3% of   31.50MiB at   29.04MiB/s ETA 00:00
[download]  30.4% of   31.50MiB at    8.01MiB/s ETA 00:02
[download]  30.6% of   31.50MiB at    6.28MiB/s ETA 00:03
[download]  31.0% of   31.50MiB at    5.93MiB/s ETA 00:03
[download]  31.8% of   31.50MiB at    5.56MiB/s ETA 00:03
[download]  33.4% of   31.50MiB at    5.33MiB/s ETA 00:03
[download]  36.6% of   31.50MiB at    4.40MiB/s ETA 00:04
[download]  42.9% of   31.50MiB at    4.32MiB/s ETA 00:04
[download]  55.6% of   31.50MiB at    4.10MiB/s ETA 00:03
[download]  60.7% of   31.50MiB at    4.12MiB/s ETA 00:03
[download]  60.7% of   31.50MiB at  994.85KiB/s ETA 00:12
[download]  60.7% of   31.50MiB at    2.91MiB/s ETA 00:04
[download]  60.7% of   31.50MiB at    6.80MiB/s ETA 00:01
[download]  60.7% of   31.50MiB at   14.57MiB/s ETA 00:00
[download]  60.7% of   31.50MiB at   15.12MiB/s ETA 00:00
[download]  60.8% of   31.50MiB at   17.43MiB/s ETA 00:00
[download]  61.0% of   31.50MiB at    6.17MiB/s ETA 00:01
[download]  61.4% of   31.50MiB at    6.71MiB/s ETA 00:01
[download]  62.2% of   31.50MiB at    5.31MiB/s ETA 00:02
[download]  63.8% of   31.50MiB at    5.83MiB/s ETA 00:01
[download]  67.0% of   31.50MiB at    4.15MiB/s ETA 00:02
[download]  73.3% of   31.50MiB at    3.74MiB/s ETA 00:02
[download]  84.2% of   31.50MiB at    2.34MiB/s ETA 00:02
[download]  89.6% of   31.50MiB at    2.32MiB/s ETA 00:01
[download]  91.0% of   31.50MiB at    2.38MiB/s ETA 00:01
[download]  91.0% of   31.50MiB at  998.64KiB/s ETA 00:02
[download]  91.0% of   31.50MiB at    1.79MiB/s ETA 00:01
[download]  91.0% of   31.50MiB at    4.17MiB/s ETA 00:00
[download]  91.0% of   31.50MiB at    6.77MiB/s ETA 00:00
[download]  91.1% of   31.50MiB at   10.81MiB/s ETA 00:00
[download]  91.2% of   31.50MiB at   10.70MiB/s ETA 00:00
[download]  91.4% of   31.50MiB at    3.80MiB/s ETA 00:00
[download]  91.8% of   31.50MiB at    4.14MiB/s ETA 00:00
[download]  92.6% of   31.50MiB at    4.18MiB/s ETA 00:00
[download]  94.1% of   31.50MiB at    3.95MiB/s ETA 00:00
[download]  97.3% of   31.50MiB at    2.26MiB/s ETA 00:00
[download] 100.0% of   31.50MiB at    2.32MiB/s ETA 00:00
[download] 100% of   31.50MiB in 00:00:11 at 2.76MiB/s
[ExtractAudio] Destination: D:\downloaded_media\audio\Memory_of_Lightwaves_~_Relaxing_FFX-2_Music_w_Ocean_and_Soft_Rain_Sounds [2B9jv7prFno].opus
Deleting original file D:\downloaded_media\audio\Memory_of_Lightwaves_~_Relaxing_FFX-2_Music_w_Ocean_and_Soft_Rain_Sounds [2B9jv7prFno].webm (pass -k to keep)

STDERR: WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one

CompletedProcess(args=['yt-dlp\\yt-dlp.exe', '-x', '--audio-format', 'best', '-o', 'D:/downloaded_media/audio/%(title)s [%(id)s].%(ext)s', '--restrict-filenames', 'https://youtu.be/2B9jv7prFno?si=VekCYNu7hpLbRNC6', '--ffmpeg-location', 'ffmpeg-8.0.1-essentials_build\\bin'], returncode=0, stdout='[youtube] Extracting URL: https://youtu.be/2B9jv7prFno?si=VekCYNu7hpLbRNC6\n[youtube] 2B9jv7prFno: Downloading webpage\n[youtube] 2B9jv7prFno: Downloading android vr player API JSON\n[info] 2B9jv7prFno: Downloading 1 format(s): 251\n[download] Destination: D:\\downloaded_media\\audio\\Memory_of_Lightwaves_~_Relaxing_FFX-2_Music_w_Ocean_and_Soft_Rain_Sounds [2B9jv7prFno].webm\n\n[download]   0.0% of   31.50MiB at  867.85KiB/s ETA 00:37\n[download]   0.0% of   31.50MiB at    2.54MiB/s ETA 00:12\n[download]   0.0% of   31.50MiB at    3.02MiB/s ETA 00:10\n[download]   0.0% of   31.50MiB at    6.47MiB/s ETA 00:04\n[download]   0.1% of   31.50MiB at  189.31KiB/s ETA 02:50\n[download]   0.2% of   31.50MiB at  381.86KiB/s ETA 01:24\n[download]   0.4% of   31.50MiB at  609.27KiB/s ETA 00:52\n[download]   0.8% of   31.50MiB at    1.05MiB/s ETA 00:29\n[download]   1.6% of   31.50MiB at    1.68MiB/s ETA 00:18\n[download]   3.2% of   31.50MiB at    1.73MiB/s ETA 00:17\n[download]   6.3% of   31.50MiB at    1.93MiB/s ETA 00:15\n[download]  12.7% of   31.50MiB at    2.31MiB/s ETA 00:11\n[download]  21.8% of   31.50MiB at    2.90MiB/s ETA 00:08\n[download]  30.2% of   31.50MiB at    2.96MiB/s ETA 00:07\n[download]  30.2% of   31.50MiB at  Unknown B/s ETA Unknown\n[download]  30.2% of   31.50MiB at  Unknown B/s ETA Unknown\n[download]  30.2% of   31.50MiB at    6.56MiB/s ETA 00:03  \n[download]  30.3% of   31.50MiB at   14.05MiB/s ETA 00:01\n[download]  30.3% of   31.50MiB at   29.04MiB/s ETA 00:00\n[download]  30.4% of   31.50MiB at    8.01MiB/s ETA 00:02\n[download]  30.6% of   31.50MiB at    6.28MiB/s ETA 00:03\n[download]  31.0% of   31.50MiB at    5.93MiB/s ETA 00:03\n[download]  31.8% of   31.50MiB at    5.56MiB/s ETA 00:03\n[download]  33.4% of   31.50MiB at    5.33MiB/s ETA 00:03\n[download]  36.6% of   31.50MiB at    4.40MiB/s ETA 00:04\n[download]  42.9% of   31.50MiB at    4.32MiB/s ETA 00:04\n[download]  55.6% of   31.50MiB at    4.10MiB/s ETA 00:03\n[download]  60.7% of   31.50MiB at    4.12MiB/s ETA 00:03\n[download]  60.7% of   31.50MiB at  994.85KiB/s ETA 00:12\n[download]  60.7% of   31.50MiB at    2.91MiB/s ETA 00:04\n[download]  60.7% of   31.50MiB at    6.80MiB/s ETA 00:01\n[download]  60.7% of   31.50MiB at   14.57MiB/s ETA 00:00\n[download]  60.7% of   31.50MiB at   15.12MiB/s ETA 00:00\n[download]  60.8% of   31.50MiB at   17.43MiB/s ETA 00:00\n[download]  61.0% of   31.50MiB at    6.17MiB/s ETA 00:01\n[download]  61.4% of   31.50MiB at    6.71MiB/s ETA 00:01\n[download]  62.2% of   31.50MiB at    5.31MiB/s ETA 00:02\n[download]  63.8% of   31.50MiB at    5.83MiB/s ETA 00:01\n[download]  67.0% of   31.50MiB at    4.15MiB/s ETA 00:02\n[download]  73.3% of   31.50MiB at    3.74MiB/s ETA 00:02\n[download]  84.2% of   31.50MiB at    2.34MiB/s ETA 00:02\n[download]  89.6% of   31.50MiB at    2.32MiB/s ETA 00:01\n[download]  91.0% of   31.50MiB at    2.38MiB/s ETA 00:01\n[download]  91.0% of   31.50MiB at  998.64KiB/s ETA 00:02\n[download]  91.0% of   31.50MiB at    1.79MiB/s ETA 00:01\n[download]  91.0% of   31.50MiB at    4.17MiB/s ETA 00:00\n[download]  91.0% of   31.50MiB at    6.77MiB/s ETA 00:00\n[download]  91.1% of   31.50MiB at   10.81MiB/s ETA 00:00\n[download]  91.2% of   31.50MiB at   10.70MiB/s ETA 00:00\n[download]  91.4% of   31.50MiB at    3.80MiB/s ETA 00:00\n[download]  91.8% of   31.50MiB at    4.14MiB/s ETA 00:00\n[download]  92.6% of   31.50MiB at    4.18MiB/s ETA 00:00\n[download]  94.1% of   31.50MiB at    3.95MiB/s ETA 00:00\n[download]  97.3% of   31.50MiB at    2.26MiB/s ETA 00:00\n[download] 100.0% of   31.50MiB at    2.32MiB/s ETA 00:00\n[download] 100% of   31.50MiB in 00:00:11 at 2.76MiB/s   \n[ExtractAudio] Destination: D:\\downloaded_media\\audio\\Memory_of_Lightwaves_~_Relaxing_FFX-2_Music_w_Ocean_and_Soft_Rain_Sounds [2B9jv7prFno].opus\nDeleting original file D:\\downloaded_media\\audio\\Memory_of_Lightwaves_~_Relaxing_FFX-2_Music_w_Ocean_and_Soft_Rain_Sounds [2B9jv7prFno].webm (pass -k to keep)\n', stderr='WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one\n')

### Download a list of audio

In [10]:
url = input("Enter Youtube playlist URL to download audios: ")
completed_process = get_playlist_urls(url)
lst_urls = list_playlist_urls(completed_process)
print("Playlist URLs:", lst_urls)

STDOUT:
STDERR: ERROR: [generic] '' is not a valid URL

No URLs found or error occurred.
Playlist URLs: []

In [11]:
for url in lst_urls:
    print(f"Downloading audio for: {url}")
    download_audio(url)

### Download a/an (unlisted) video

In [9]:
url = input("Enter best video URL to download: ")
download_best_video(url, output_dir='unlisted')

STDOUT: [telegram:embed] Extracting URL: https://t.me/Huseyinjjk/6
[telegram:embed] 6: Downloading embed frame
[info] 6: Downloading 1 format(s): 0
[download] Destination: D:\downloaded_media\unlisted\Hyperos_theme_backup_installation [6].mp4

[download]   0.0% of    9.15MiB at  Unknown B/s ETA Unknown
[download]   0.0% of    9.15MiB at  Unknown B/s ETA Unknown
[download]   0.1% of    9.15MiB at  Unknown B/s ETA Unknown
[download]   0.2% of    9.15MiB at  Unknown B/s ETA Unknown
[download]   0.3% of    9.15MiB at  185.24KiB/s ETA 00:50
[download]   0.7% of    9.15MiB at  240.87KiB/s ETA 00:38
[download]   1.4% of    9.15MiB at  297.71KiB/s ETA 00:31
[download]   2.7% of    9.15MiB at  386.28KiB/s ETA 00:23
[download]   5.5% of    9.15MiB at  615.51KiB/s ETA 00:14
[download]  10.9% of    9.15MiB at    1.00MiB/s ETA 00:08
[download]  21.9% of    9.15MiB at    1.64MiB/s ETA 00:04
[download]  43.7% of    9.15MiB at    2.42MiB/s ETA 00:02
[download]  87.5% of    9.15MiB at    3.88MiB/s ETA 00:00
[download] 100.0% of    9.15MiB at    4.19MiB/s ETA 00:00
[download] 100% of    9.15MiB in 00:00:02 at 3.31MiB/s
[VideoConvertor] Not converting media file "D:\downloaded_media\unlisted\Hyperos_theme_backup_installation [6].mp4"; already is in target format mp4

CompletedProcess(args=['yt-dlp\\yt-dlp.exe', '--cookies', 'twitter_cookies.txt', '--no-playlist', '--merge-output-format', 'mp4', '-o', 'D:/downloaded_media/unlisted/%(title)s [%(id)s].%(ext)s', '--restrict-filenames', '--recode-video', 'mp4', '-f', 'bestvideo+bestaudio/best', 'https://t.me/Huseyinjjk/6', '--ffmpeg-location', 'ffmpeg-8.0-essentials_build\\bin'], returncode=0, stdout='[telegram:embed] Extracting URL: https://t.me/Huseyinjjk/6\n[telegram:embed] 6: Downloading embed frame\n[info] 6: Downloading 1 format(s): 0\n[download] Destination: D:\\downloaded_media\\unlisted\\Hyperos_theme_backup_installation [6].mp4\n\n[download]   0.0% of    9.15MiB at  Unknown B/s ETA Unknown\n[download]   0.0% of    9.15MiB at  Unknown B/s ETA Unknown\n[download]   0.1% of    9.15MiB at  Unknown B/s ETA Unknown\n[download]   0.2% of    9.15MiB at  Unknown B/s ETA Unknown\n[download]   0.3% of    9.15MiB at  185.24KiB/s ETA 00:50  \n[download]   0.7% of    9.15MiB at  240.87KiB/s ETA 00:38\n[download]   1.4% of    9.15MiB at  297.71KiB/s ETA 00:31\n[download]   2.7% of    9.15MiB at  386.28KiB/s ETA 00:23\n[download]   5.5% of    9.15MiB at  615.51KiB/s ETA 00:14\n[download]  10.9% of    9.15MiB at    1.00MiB/s ETA 00:08\n[download]  21.9% of    9.15MiB at    1.64MiB/s ETA 00:04\n[download]  43.7% of    9.15MiB at    2.42MiB/s ETA 00:02\n[download]  87.5% of    9.15MiB at    3.88MiB/s ETA 00:00\n[download] 100.0% of    9.15MiB at    4.19MiB/s ETA 00:00\n[download] 100% of    9.15MiB in 00:00:02 at 3.31MiB/s   \n[VideoConvertor] Not converting media file "D:\\downloaded_media\\unlisted\\Hyperos_theme_backup_installation [6].mp4"; already is in target format mp4\n', stderr='')

### S4 video download

In [13]:
root_dir = r"C:\Users\rob_t\repos\s4_ielts_scraping"
completed_file = r"s4_completed.xlsx"
completed_file = os.path.join(root_dir, completed_file)
completed_df = pd.read_excel(io=completed_file, engine='openpyxl', sheet_name="Sheet1")
display(completed_df)

,test_set,test_part,test_url,ytb_url
0,Practice Set 3 Test 1,Practice Set 3 Test 1 Q1-5,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/A1vZY9uwIiw
1,Practice Set 3 Test 1,Practice Set 3 Test 1 Q6-9,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/CLV_btHqDrM
2,Practice Set 3 Test 1,Practice Set 3 Test 1 Q10-13,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/jVU7fQhPjA8
3,Practice Set 3 Test 1,Practice Set 3 Test 1 Q14-18,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/wImq9vRLZtY
4,Practice Set 3 Test 1,Practice Set 3 Test 1 Q19-22,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/CDmjzgvCttI
...,...,...,...,...
1105,BC Test 9,BC Test 9 Q11-14,https://study4.com/courses/15/ielts-intensive-...,https://youtu.be/cEd27QfHhZM
1106,BC Test 9,BC Test 9 Q15-17,https://study4.com/courses/15/ielts-intensive-...,https://youtu.be/02c0MNxwc-o
1107,BC Test 9,BC Test 9 Q18-20,https://study4.com/courses/15/ielts-intensive-...,https://youtu.be/G0v6Mzo_yIM
1108,BC Test 9,BC Test 9 Q21-30,https://study4.com/courses/15/ielts-intensive-...,https://youtu.be/ur5yFrTPQR8
1109,BC Test 9,BC Test 9 Q31-40,https://study4.com/courses/15/ielts-intensive-...,https://youtu.be/qhTmVHounpw

In [14]:
# src_file = r"s4_listening_ytb_urls.xlsx"
src_file = r"s4_reading_ytb_urls.xlsx"
src_file = os.path.join(root_dir, src_file)
test_str = "BC Test"
src_df = pd.read_excel(io=src_file, engine='openpyxl', sheet_name="Sheet1")
print("Total rows:", len(src_df))
src_df = src_df[~src_df['ytb_url'].isin(completed_df['ytb_url'])]
print("Remaining rows:", len(src_df))
src_df

Total rows: 706
Remaining rows: 168

,test_set,test_part,test_url,ytb_url
535,BC Test 1,BC Test 1 Q1-7,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/51oNKTD7EuA
536,BC Test 1,BC Test 1 Q8-13,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/dlzmmBEK_RE
537,BC Test 1,BC Test 1 Q14-22,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/dhSABSpBbFI
538,BC Test 1,BC Test 1 Q23-26,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/3SpeIzu8eOk
539,BC Test 1,BC Test 1 Q27-31,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/GZDQvEU-Swo
...,...,...,...,...
701,IT2 Test 6,IT2 Test 6 Q20-23,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/ycG9ICA33cA
702,IT2 Test 6,IT2 Test 6 Q24-26,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/X6nCuP2omck
703,IT2 Test 6,IT2 Test 6 Q27-32,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/Gjlewcyhokk
704,IT2 Test 6,IT2 Test 6 Q33-36,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/uWPxtemuMkY
705,IT2 Test 6,IT2 Test 6 Q37-40,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/cMp0DTAXKDk

In [15]:
filtered_df = src_df[src_df['test_set'].str.contains(test_str)]
filtered_df.reset_index(drop=True, inplace=True)
filtered_df

,test_set,test_part,test_url,ytb_url
0,BC Test 1,BC Test 1 Q1-7,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/51oNKTD7EuA
1,BC Test 1,BC Test 1 Q8-13,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/dlzmmBEK_RE
2,BC Test 1,BC Test 1 Q14-22,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/dhSABSpBbFI
3,BC Test 1,BC Test 1 Q23-26,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/3SpeIzu8eOk
4,BC Test 1,BC Test 1 Q27-31,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/GZDQvEU-Swo
...,...,...,...,...
67,BC Test 9,BC Test 9 Q22-26,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/rpmzrD_ZvMk
68,BC Test 9,BC Test 9 Q27-31,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/ZMe8pbblJ4A
69,BC Test 9,BC Test 9 Q32-36,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/dZ2RjXgOJGk
70,BC Test 9,BC Test 9 Q37-39,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/y3_qDAttuQo
71,BC Test 9,BC Test 9 Q40,https://study4.com/courses/22/ielts-intensive-...,https://youtu.be/lggtdXVLEyc

In [16]:
for row in filtered_df.iterrows():
    download_best_video(url=row[1]['ytb_url'], output_dir='unlisted')
    completed_df = pd.concat([completed_df, pd.DataFrame([row[1]])], ignore_index=True)
    time.sleep(random.randint(10, 15))

completed_df.to_excel(completed_file, index=False)

STDOUT: [youtube] Extracting URL: https://youtu.be/51oNKTD7EuA
[youtube] 51oNKTD7EuA: Downloading webpage
[youtube] 51oNKTD7EuA: Downloading tv downgraded player API JSON
[youtube] 51oNKTD7EuA: Downloading player 1ebf2aa6-main
[youtube] [jsc:node] Solving JS challenges using node
[youtube] 51oNKTD7EuA: Downloading m3u8 information
[info] 51oNKTD7EuA: Downloading 1 format(s): 136+251
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q1_Q7_TFNG [51oNKTD7EuA].f136.mp4

[download]   0.0% of   24.96MiB at  998.17KiB/s ETA 00:51
[download]   0.0% of   24.96MiB at  999.75KiB/s ETA 00:25
[download]   0.0% of   24.96MiB at    1.71MiB/s ETA 00:14
[download]   0.1% of   24.96MiB at    2.93MiB/s ETA 00:08
[download]   0.1% of   24.96MiB at    5.05MiB/s ETA 00:04
[download]   0.2% of   24.96MiB at    5.57MiB/s ETA 00:04
[download]   0.5% of   24.96MiB at    6.87MiB/s ETA 00:03
[download]   1.0% of   24.96MiB at   10.36MiB/s ETA 00:02
[download]   2.0% of   24.96MiB at   16.28MiB/s ETA 00:01
[download]   4.0% of   24.96MiB at   15.50MiB/s ETA 00:01
[download]   8.0% of   24.96MiB at    7.99MiB/s ETA 00:02
[download]  16.0% of   24.96MiB at    9.17MiB/s ETA 00:02
[download]  32.0% of   24.96MiB at    8.39MiB/s ETA 00:02
[download]  39.3% of   24.96MiB at    9.07MiB/s ETA 00:01
[download]  39.4% of   24.96MiB at  Unknown B/s ETA Unknown
[download]  39.4% of   24.96MiB at  Unknown B/s ETA Unknown
[download]  39.4% of   24.96MiB at  Unknown B/s ETA Unknown
[download]  39.4% of   24.96MiB at    7.33MiB/s ETA 00:02
[download]  39.5% of   24.96MiB at   15.16MiB/s ETA 00:00
[download]  39.6% of   24.96MiB at   20.53MiB/s ETA 00:00
[download]  39.8% of   24.96MiB at   41.39MiB/s ETA 00:00
[download]  40.3% of   24.96MiB at    3.34MiB/s ETA 00:04
[download]  41.3% of   24.96MiB at    5.46MiB/s ETA 00:02
[download]  43.3% of   24.96MiB at    7.98MiB/s ETA 00:01
[download]  47.4% of   24.96MiB at   10.26MiB/s ETA 00:01
[download]  55.4% of   24.96MiB at   10.03MiB/s ETA 00:01
[download]  71.4% of   24.96MiB at    9.12MiB/s ETA 00:00
[download]  79.3% of   24.96MiB at    9.07MiB/s ETA 00:00
[download]  79.3% of   24.96MiB at  Unknown B/s ETA Unknown
[download]  79.4% of   24.96MiB at  Unknown B/s ETA Unknown
[download]  79.4% of   24.96MiB at  Unknown B/s ETA Unknown
[download]  79.4% of   24.96MiB at   14.65MiB/s ETA 00:00
[download]  79.5% of   24.96MiB at   30.27MiB/s ETA 00:00
[download]  79.6% of   24.96MiB at   61.51MiB/s ETA 00:00
[download]  79.8% of   24.96MiB at  124.00MiB/s ETA 00:00
[download]  80.3% of   24.96MiB at    1.42MiB/s ETA 00:03
[download]  81.3% of   24.96MiB at    2.59MiB/s ETA 00:01
[download]  83.3% of   24.96MiB at    4.39MiB/s ETA 00:00
[download]  87.4% of   24.96MiB at    6.77MiB/s ETA 00:00
[download]  95.4% of   24.96MiB at    7.79MiB/s ETA 00:00
[download] 100.0% of   24.96MiB at    7.59MiB/s ETA 00:00
[download] 100% of   24.96MiB in 00:00:03 at 7.64MiB/s
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q1_Q7_TFNG [51oNKTD7EuA].f251.webm

[download]   0.0% of   13.57MiB at  525.08KiB/s ETA 00:26
[download]   0.0% of   13.57MiB at  754.69KiB/s ETA 00:18
[download]   0.1% of   13.57MiB at    1.15MiB/s ETA 00:11
[download]   0.1% of   13.57MiB at    2.12MiB/s ETA 00:06
[download]   0.2% of   13.57MiB at    3.84MiB/s ETA 00:03
[download]   0.5% of   13.57MiB at    4.76MiB/s ETA 00:02
[download]   0.9% of   13.57MiB at    6.37MiB/s ETA 00:02
[download]   1.8% of   13.57MiB at    9.06MiB/s ETA 00:01
[download]   3.7% of   13.57MiB at   14.06MiB/s ETA 00:00
[download]   7.4% of   13.57MiB at   15.60MiB/s ETA 00:00
[download]  14.7% of   13.57MiB at    8.14MiB/s ETA 00:01
[download]  29.5% of   13.57MiB at    5.41MiB/s ETA 00:01
[download]  58.9% of   13.57MiB at    3.92MiB/s ETA 00:01
[download]  72.4% of   13.57MiB at    4.59MiB/s ETA 00:00
[download]  72.4% of   13.57MiB at  Unknown B/s ETA Unknown
[download]  72.4% of   13.57MiB at  Unknown B/s ETA Unknown
[download]  72.5% of   13.57MiB at  Unknown B/s ETA Unknown
[download]  72.5% of   13.57MiB at    7.57MiB/s ETA 00:00
[download]  72.6% of   13.57MiB at   10.32MiB/s ETA 00:00
[download]  72.9% of   13.57MiB at   15.62MiB/s ETA 00:00
[download]  73.3% of   13.57MiB at   31.49MiB/s ETA 00:00
[download]  74.2% of   13.57MiB at  640.78KiB/s ETA 00:05
[download]  76.1% of   13.57MiB at    1.20MiB/s ETA 00:02
[download]  79.8% of   13.57MiB at    2.22MiB/s ETA 00:01
[download]  87.1% of   13.57MiB at    3.87MiB/s ETA 00:00
[download] 100.0% of   13.57MiB at    3.71MiB/s ETA 00:00
[download] 100% of   13.57MiB in 00:00:04 at 3.36MiB/s
[Merger] Merging formats into "D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q1_Q7_TFNG [51oNKTD7EuA].mp4"
Deleting original file D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q1_Q7_TFNG [51oNKTD7EuA].f251.webm (pass -k to keep)
Deleting original file D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q1_Q7_TFNG [51oNKTD7EuA].f136.mp4 (pass -k to keep)
[VideoConvertor] Not converting media file "D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q1_Q7_TFNG [51oNKTD7EuA].mp4"; already is in target format mp4

STDOUT: [youtube] Extracting URL: https://youtu.be/dlzmmBEK_RE
[youtube] dlzmmBEK_RE: Downloading webpage
[youtube] dlzmmBEK_RE: Downloading tv downgraded player API JSON
[youtube] dlzmmBEK_RE: Downloading player 1ebf2aa6-main
[youtube] [jsc:node] Solving JS challenges using node
[youtube] dlzmmBEK_RE: Downloading m3u8 information
[info] dlzmmBEK_RE: Downloading 1 format(s): 136+251
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q8_Q13_Multiple_Choices [dlzmmBEK_RE].f136.mp4

[download]   0.0% of   39.10MiB at  Unknown B/s ETA Unknown
[download]   0.0% of   39.10MiB at    2.93MiB/s ETA 00:13
[download]   0.0% of   39.10MiB at    6.83MiB/s ETA 00:05
[download]   0.0% of   39.10MiB at   14.65MiB/s ETA 00:02
[download]   0.1% of   39.10MiB at    4.32MiB/s ETA 00:09
[download]   0.2% of   39.10MiB at    5.12MiB/s ETA 00:07
[download]   0.3% of   39.10MiB at    6.89MiB/s ETA 00:05
[download]   0.6% of   39.10MiB at   10.16MiB/s ETA 00:03
[download]   1.3% of   39.10MiB at    7.06MiB/s ETA 00:05
[download]   2.6% of   39.10MiB at    9.57MiB/s ETA 00:03
[download]   5.1% of   39.10MiB at   11.70MiB/s ETA 00:03
[download]  10.2% of   39.10MiB at    4.63MiB/s ETA 00:07
[download]  17.6% of   39.10MiB at    3.34MiB/s ETA 00:09
[download]  23.8% of   39.10MiB at    3.21MiB/s ETA 00:09
[download]  25.5% of   39.10MiB at    3.40MiB/s ETA 00:08
[download]  25.5% of   39.10MiB at  Unknown B/s ETA Unknown
[download]  25.5% of   39.10MiB at    1.46MiB/s ETA 00:19
[download]  25.5% of   39.10MiB at    2.28MiB/s ETA 00:12
[download]  25.6% of   39.10MiB at    2.93MiB/s ETA 00:09
[download]  25.6% of   39.10MiB at    5.05MiB/s ETA 00:05
[download]  25.7% of   39.10MiB at    7.69MiB/s ETA 00:03
[download]  25.8% of   39.10MiB at   13.77MiB/s ETA 00:02
[download]  26.2% of   39.10MiB at   22.63MiB/s ETA 00:01
[download]  26.8% of   39.10MiB at   17.96MiB/s ETA 00:01
[download]  28.1% of   39.10MiB at    9.37MiB/s ETA 00:03
[download]  30.6% of   39.10MiB at    2.99MiB/s ETA 00:09
[download]  35.2% of   39.10MiB at    4.79MiB/s ETA 00:05
[download]  44.3% of   39.10MiB at    3.34MiB/s ETA 00:06
[download]  50.7% of   39.10MiB at    3.38MiB/s ETA 00:05
[download]  50.9% of   39.10MiB at    3.39MiB/s ETA 00:05
[download]  50.9% of   39.10MiB at  Unknown B/s ETA Unknown
[download]  50.9% of   39.10MiB at    1.46MiB/s ETA 00:13
[download]  50.9% of   39.10MiB at    1.71MiB/s ETA 00:11
[download]  50.9% of   39.10MiB at    2.93MiB/s ETA 00:06
[download]  51.0% of   39.10MiB at    4.32MiB/s ETA 00:04
[download]  51.0% of   39.10MiB at    6.83MiB/s ETA 00:02
[download]  51.2% of   39.10MiB at  256.99KiB/s ETA 01:16
[download]  51.5% of   39.10MiB at  506.78KiB/s ETA 00:38
[download]  52.2% of   39.10MiB at  961.70KiB/s ETA 00:19
[download]  53.4% of   39.10MiB at    1.77MiB/s ETA 00:10
[download]  56.0% of   39.10MiB at    3.16MiB/s ETA 00:05
[download]  61.1% of   39.10MiB at    3.12MiB/s ETA 00:04
[download]  69.0% of   39.10MiB at    2.79MiB/s ETA 00:04
[download]  75.2% of   39.10MiB at    2.89MiB/s ETA 00:03
[download]  76.2% of   39.10MiB at    2.98MiB/s ETA 00:03
[download]  76.2% of   39.10MiB at  Unknown B/s ETA Unknown
[download]  76.2% of   39.10MiB at  Unknown B/s ETA Unknown
[download]  76.2% of   39.10MiB at    6.83MiB/s ETA 00:01
[download]  76.2% of   39.10MiB at   14.64MiB/s ETA 00:00
[download]  76.3% of   39.10MiB at   30.26MiB/s ETA 00:00
[download]  76.4% of   39.10MiB at   61.50MiB/s ETA 00:00
[download]  76.5% of   39.10MiB at   20.67MiB/s ETA 00:00
[download]  76.8% of   39.10MiB at  466.69KiB/s ETA 00:19
[download]  77.4% of   39.10MiB at  875.57KiB/s ETA 00:10
[download]  78.6% of   39.10MiB at    1.59MiB/s ETA 00:05
[download]  81.0% of   39.10MiB at    2.85MiB/s ETA 00:02
[download]  85.7% of   39.10MiB at    2.88MiB/s ETA 00:01
[download]  93.2% of   39.10MiB at    2.40MiB/s ETA 00:01
[download]  98.2% of   39.10MiB at    2.50MiB/s ETA 00:00
[download] 100.0% of   39.10MiB at    2.66MiB/s ETA 00:00
[download] 100% of   39.10MiB in 00:00:14 at 2.78MiB/s
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q8_Q13_Multiple_Choices [dlzmmBEK_RE].f251.webm

[download]   0.0% of   16.01MiB at  988.76KiB/s ETA 00:16
[download]   0.0% of   16.01MiB at    1.46MiB/s ETA 00:10
[download]   0.0% of   16.01MiB at    2.27MiB/s ETA 00:07
[download]   0.1% of   16.01MiB at    4.87MiB/s ETA 00:03
[download]   0.2% of   16.01MiB at    7.55MiB/s ETA 00:02
[download]   0.4% of   16.01MiB at   12.28MiB/s ETA 00:01
[download]   0.8% of   16.01MiB at   20.62MiB/s ETA 00:00
[download]   1.6% of   16.01MiB at   20.79MiB/s ETA 00:00
[download]   3.1% of   16.01MiB at   16.91MiB/s ETA 00:00
[download]   6.2% of   16.01MiB at   15.69MiB/s ETA 00:00
[download]  12.5% of   16.01MiB at   11.84MiB/s ETA 00:01
[download]  25.0% of   16.01MiB at    3.52MiB/s ETA 00:03
[download]  37.9% of   16.01MiB at    2.51MiB/s ETA 00:03
[download]  48.0% of   16.01MiB at    3.04MiB/s ETA 00:02
[download]  59.8% of   16.01MiB at    2.98MiB/s ETA 00:02
[download]  59.8% of   16.01MiB at  Unknown B/s ETA Unknown
[download]  59.8% of   16.01MiB at  Unknown B/s ETA Unknown
[download]  59.8% of   16.01MiB at    2.28MiB/s ETA 00:02
[download]  59.9% of   16.01MiB at    3.66MiB/s ETA 00:01
[download]  60.0% of   16.01MiB at    5.05MiB/s ETA 00:01
[download]  60.2% of   16.01MiB at    8.79MiB/s ETA 00:00
[download]  60.6% of   16.01MiB at   15.50MiB/s ETA 00:00
[download]  61.4% of   16.01MiB at   22.64MiB/s ETA 00:00
[download]  62.9% of   16.01MiB at  801.89KiB/s ETA 00:07
[download]  65.4% of   16.01MiB at    1.35MiB/s ETA 00:04
[download]  70.4% of   16.01MiB at    2.34MiB/s ETA 00:02
[download]  80.4% of   16.01MiB at    2.44MiB/s ETA 00:01
[download]  96.3% of   16.01MiB at    2.37MiB/s ETA 00:00
[download] 100.0% of   16.01MiB at    2.16MiB/s ETA 00:00
[download] 100% of   16.01MiB in 00:00:06 at 2.35MiB/s
[Merger] Merging formats into "D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q8_Q13_Multiple_Choices [dlzmmBEK_RE].mp4"
Deleting original file D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q8_Q13_Multiple_Choices [dlzmmBEK_RE].f251.webm (pass -k to keep)
Deleting original file D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q8_Q13_Multiple_Choices [dlzmmBEK_RE].f136.mp4 (pass -k to keep)
[VideoConvertor] Not converting media file "D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q8_Q13_Multiple_Choices [dlzmmBEK_RE].mp4"; already is in target format mp4

STDOUT: [youtube] Extracting URL: https://youtu.be/dhSABSpBbFI
[youtube] dhSABSpBbFI: Downloading webpage
[youtube] dhSABSpBbFI: Downloading tv downgraded player API JSON
[youtube] dhSABSpBbFI: Downloading player 1ebf2aa6-main
[youtube] [jsc:node] Solving JS challenges using node
[youtube] dhSABSpBbFI: Downloading m3u8 information
[info] dhSABSpBbFI: Downloading 1 format(s): 136+251
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q14_Q22_Matching_features [dhSABSpBbFI].f136.mp4

[download]   0.0% of   39.52MiB at  249.91KiB/s ETA 02:41
[download]   0.0% of   39.52MiB at  598.87KiB/s ETA 01:07
[download]   0.0% of   39.52MiB at    1.14MiB/s ETA 00:34
[download]   0.0% of   39.52MiB at    1.83MiB/s ETA 00:21
[download]   0.1% of   39.52MiB at  590.47KiB/s ETA 01:08
[download]   0.2% of   39.52MiB at  660.77KiB/s ETA 01:01
[download]   0.3% of   39.52MiB at  896.72KiB/s ETA 00:44
[download]   0.6% of   39.52MiB at    1.25MiB/s ETA 00:31
[download]   1.3% of   39.52MiB at    1.90MiB/s ETA 00:20
[download]   2.5% of   39.52MiB at    3.05MiB/s ETA 00:12
[download]   5.1% of   39.52MiB at    5.08MiB/s ETA 00:07
[download]  10.1% of   39.52MiB at    4.19MiB/s ETA 00:08
[download]  19.1% of   39.52MiB at    4.75MiB/s ETA 00:06
[download]  25.1% of   39.52MiB at    5.52MiB/s ETA 00:05
[download]  25.1% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  25.1% of   39.52MiB at    1.46MiB/s ETA 00:30
[download]  25.1% of   39.52MiB at    1.71MiB/s ETA 00:17
[download]  25.1% of   39.52MiB at    2.44MiB/s ETA 00:12
[download]  25.1% of   39.52MiB at    4.33MiB/s ETA 00:06
[download]  25.2% of   39.52MiB at    7.69MiB/s ETA 00:03
[download]  25.4% of   39.52MiB at  277.81KiB/s ETA 01:48
[download]  25.7% of   39.52MiB at  554.17KiB/s ETA 00:54
[download]  26.3% of   39.52MiB at    1.07MiB/s ETA 00:27
[download]  27.6% of   39.52MiB at    2.09MiB/s ETA 00:13
[download]  30.1% of   39.52MiB at    3.91MiB/s ETA 00:07
[download]  35.2% of   39.52MiB at    3.74MiB/s ETA 00:06
[download]  44.3% of   39.52MiB at    4.95MiB/s ETA 00:04
[download]  49.7% of   39.52MiB at    5.00MiB/s ETA 00:03
[download]  49.7% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  49.7% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  49.7% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  49.8% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  49.8% of   39.52MiB at   15.14MiB/s ETA 00:01
[download]  49.9% of   39.52MiB at   30.77MiB/s ETA 00:00
[download]  50.0% of   39.52MiB at   41.35MiB/s ETA 00:00
[download]  50.3% of   39.52MiB at   41.51MiB/s ETA 00:00
[download]  51.0% of   39.52MiB at    8.08MiB/s ETA 00:02
[download]  52.2% of   39.52MiB at   13.76MiB/s ETA 00:01
[download]  54.8% of   39.52MiB at   20.46MiB/s ETA 00:00
[download]  59.8% of   39.52MiB at    8.09MiB/s ETA 00:01
[download]  70.0% of   39.52MiB at    7.05MiB/s ETA 00:01
[download]  74.5% of   39.52MiB at    6.09MiB/s ETA 00:01
[download]  74.5% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  74.5% of   39.52MiB at  749.74KiB/s ETA 00:13
[download]  74.5% of   39.52MiB at  999.70KiB/s ETA 00:10
[download]  74.6% of   39.52MiB at    1.47MiB/s ETA 00:06
[download]  74.6% of   39.52MiB at    2.52MiB/s ETA 00:03
[download]  74.7% of   39.52MiB at    4.40MiB/s ETA 00:02
[download]  74.8% of   39.52MiB at    7.30MiB/s ETA 00:01
[download]  75.1% of   39.52MiB at   12.46MiB/s ETA 00:00
[download]  75.8% of   39.52MiB at   22.69MiB/s ETA 00:00
[download]  77.0% of   39.52MiB at   18.90MiB/s ETA 00:00
[download]  79.6% of   39.52MiB at   28.22MiB/s ETA 00:00
[download]  84.6% of   39.52MiB at    7.60MiB/s ETA 00:00
[download]  94.8% of   39.52MiB at    6.73MiB/s ETA 00:00
[download]  98.6% of   39.52MiB at    6.57MiB/s ETA 00:00
[download]  98.6% of   39.52MiB at  Unknown B/s ETA Unknown
[download]  98.6% of   39.52MiB at    1.46MiB/s ETA 00:00
[download]  98.6% of   39.52MiB at    2.28MiB/s ETA 00:00
[download]  98.6% of   39.52MiB at    2.93MiB/s ETA 00:00
[download]  98.7% of   39.52MiB at    4.32MiB/s ETA 00:00
[download]  98.7% of   39.52MiB at    6.14MiB/s ETA 00:00
[download]  98.9% of   39.52MiB at    9.53MiB/s ETA 00:00
[download]  99.2% of   39.52MiB at   17.78MiB/s ETA 00:00
[download]  99.8% of   39.52MiB at   33.25MiB/s ETA 00:00
[download] 100.0% of   39.52MiB at   35.03MiB/s ETA 00:00
[download] 100% of   39.52MiB in 00:00:08 at 4.75MiB/s
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q14_Q22_Matching_features [dhSABSpBbFI].f251.webm

[download]   0.0% of   17.33MiB at  499.98KiB/s ETA 00:35
[download]   0.0% of   17.33MiB at  599.96KiB/s ETA 00:29
[download]   0.0% of   17.33MiB at 1000.00KiB/s ETA 00:17
[download]   0.1% of   17.33MiB at    1.63MiB/s ETA 00:10
[download]   0.2% of   17.33MiB at    2.75MiB/s ETA 00:06
[download]   0.4% of   17.33MiB at    4.73MiB/s ETA 00:03
[download]   0.7% of   17.33MiB at    3.25MiB/s ETA 00:05
[download]   1.4% of   17.33MiB at    3.08MiB/s ETA 00:05
[download]   2.9% of   17.33MiB at    4.08MiB/s ETA 00:04
[download]   5.8% of   17.33MiB at    5.64MiB/s ETA 00:02
[download]  11.5% of   17.33MiB at    7.71MiB/s ETA 00:01
[download]  23.1% of   17.33MiB at    5.69MiB/s ETA 00:02
[download]  46.2% of   17.33MiB at    7.65MiB/s ETA 00:01
[download]  56.3% of   17.33MiB at    8.35MiB/s ETA 00:00
[download]  56.3% of   17.33MiB at  Unknown B/s ETA Unknown
[download]  56.3% of   17.33MiB at    2.92MiB/s ETA 00:02
[download]  56.3% of   17.33MiB at    3.41MiB/s ETA 00:02
[download]  56.3% of   17.33MiB at    7.31MiB/s ETA 00:01
[download]  56.4% of   17.33MiB at   10.08MiB/s ETA 00:00
[download]  56.6% of   17.33MiB at   15.38MiB/s ETA 00:00
[download]  57.0% of   17.33MiB at   24.80MiB/s ETA 00:00
[download]  57.7% of   17.33MiB at   41.51MiB/s ETA 00:00
[download]  59.1% of   17.33MiB at    4.06MiB/s ETA 00:01
[download]  62.0% of   17.33MiB at    6.40MiB/s ETA 00:01
[download]  67.8% of   17.33MiB at    8.94MiB/s ETA 00:00
[download]  79.3% of   17.33MiB at   10.88MiB/s ETA 00:00
[download] 100.0% of   17.33MiB at    9.15MiB/s ETA 00:00
[download] 100% of   17.33MiB in 00:00:02 at 7.10MiB/s
[Merger] Merging formats into "D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q14_Q22_Matching_features [dhSABSpBbFI].mp4"
Deleting original file D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q14_Q22_Matching_features [dhSABSpBbFI].f136.mp4 (pass -k to keep)
Deleting original file D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q14_Q22_Matching_features [dhSABSpBbFI].f251.webm (pass -k to keep)
[VideoConvertor] Not converting media file "D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q14_Q22_Matching_features [dhSABSpBbFI].mp4"; already is in target format mp4

STDOUT: [youtube] Extracting URL: https://youtu.be/3SpeIzu8eOk
[youtube] 3SpeIzu8eOk: Downloading webpage
[youtube] 3SpeIzu8eOk: Downloading tv downgraded player API JSON
[youtube] 3SpeIzu8eOk: Downloading player 1ebf2aa6-main
[youtube] [jsc:node] Solving JS challenges using node
[youtube] 3SpeIzu8eOk: Downloading m3u8 information
[info] 3SpeIzu8eOk: Downloading 1 format(s): 136+251
[download] Destination: D:\downloaded_media\unlisted\RITrti1_reading_Test_1_Q23_Q26_Sentence_Completion [3SpeIzu8eOk].f136.mp4

[download]   0.0% of   26.98MiB at  481.99KiB/s ETA 00:57
[download]   0.0% of   26.98MiB at  736.88KiB/s ETA 00:37
[download]   0.0% of   26.98MiB at    1.32MiB/s ETA 00:20
[download]   0.1% of   26.98MiB at    2.04MiB/s ETA 00:13
[download]   0.1% of   26.98MiB at    2.98MiB/s ETA 00:09
[download]   0.2% of   26.98MiB at    5.06MiB/s ETA 00:05
[download]   0.5% of   26.98MiB at    8.18MiB/s ETA 00:03
[download]   0.9% of   26.98MiB at   12.08MiB/s ETA 00:02
[download]   1.8% of   26.98MiB at   17.84MiB/s ETA 00:01
[download]   3.7% of   26.98MiB at   10.07MiB/s ETA 00:02
[download]   7.4% of   26.98MiB at    8.83MiB/s ETA 00:02
[download]  14.8% of   26.98MiB at    6.80MiB/s ETA 00:03
[download]  29.7% of   26.98MiB at    4.07MiB/s ETA 00:04
[download]  37.0% of   26.98MiB at    3.93MiB/s ETA 00:04
[download]  37.0% of   26.98MiB at  Unknown B/s ETA Unknown
[download]  37.0% of   26.98MiB at  Unknown B/s ETA Unknown
[download]  37.0% of   26.98MiB at    6.83MiB/s ETA 00:02
[download]  37.0% of   26.98MiB at   14.64MiB/s ETA 00:01